optimize_ci:
  runs-on: macos-latest
  outputs:
    skip: ${{ steps.check_skip.outputs.skip }}
  steps:
    - name: Optimize CI
      id: check_skip
      uses: withgraphite/graphite-ci-action@main
      with:
        graphite_token: ${{ secrets.GRAPHITE_TOKEN }}
