name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  qodana:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with: # Uncomment the linter you wish to use
           args: --linter,jetbrains/qodana-jvm:2024.3
          # args: --linter,jetbrains/qodana-jvm-community:2024.3
          # args: --linter,jetbrains/qodana-jvm-android:2024.3
          # args: --linter,jetbrains/qodana-android:2024.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}